
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/jeanlaurent/stupid
    steps:
      - checkout
      - run: make build
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /go/src/github.com/jeanlaurent/stupid/bin